name: Flutter Build and Release APP

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build_and_release:
    name: Build, Upload, and Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate Firebase
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json
          gcloud auth activate-service-account --key-file=$HOME/firebase-key.json
          gcloud --quiet config set project "dvt-weather-assessment"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json

      - name: Install FlutterFire CLI
        run: dart pub global activate flutterfire_cli

      - name: Generate Firebase options
        run: flutterfire configure --project=dvt-weather-assessment --yes

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-app
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
          body: "Release ${{ github.ref_name }}"